### ISSUE TITLE
Define resource metadata schema extensions

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/stories-ui#6]
```yaml
resource_fields:
  # Standard CKAN resource fields
  - field_name: url
    label: URL
    preset: resource_url_upload
  - field_name: name
    label: Name
    form_placeholder: eg. Interview Recording - January 2025
  - field_name: description
    label: Description
    form_snippet: markdown.html
    form_placeholder: Some useful notes about the audio file
  - field_name: format
    label: Format
    preset: resource_format_autocomplete

  # Transcription metadata fields
  - field_name: transcription_tapis_job_id
    label: Transcription Job ID
    help_text: Internal TAPIS job identifier for tracking transcription requests
    validators: ignore_missing unicode_safe
    form_snippet: null  # Hidden from form - system field only
    display_snippet: null  # Hidden from display

  - field_name: transcription_status
    label: Transcription Status
    help_text: Current status of the transcription process
    validators: ignore_missing unicode_safe
    preset: select
    choices:
      - value: none
        label: Not Started
      - value: pending
        label: Processing
      - value: complete
        label: Complete
      - value: failed
        label: Failed
    form_snippet: null  # System managed field
    display_snippet: scheming/display_snippets/select.html
    
  - field_name: transcription_completed
    label: Transcription Completed
    help_text: When the transcription was completed
    validators: ignore_missing isodate
    output_validators: isodate
    form_snippet: null  # System managed field
    display_snippet: scheming/display_snippets/date.html

  - field_name: transcription_text
    label: Transcript
    help_text: The transcribed text content from the audio file
    validators: ignore_missing unicode_safe
    form_snippet: markdown.html
    display_snippet: scheming/display_snippets/markdown.html
    form_placeholder: Transcript will appear here after processing...

  - field_name: transcription_json
    label: Detailed Transcription Data
    help_text: Complete JSON output from Whisper including timing and confidence data
    validators: ignore_missing json_validator
    output_validators: json_validator
    preset: json_object
    form_snippet: null  # Too complex for manual editing
    display_snippet: null  # Raw JSON not useful for display

  - field_name: transcription_error
    label: Transcription Error
    help_text: Error details if transcription failed
    validators: ignore_missing json_validator
    output_validators: json_validator
    preset: json_object
    form_snippet: null  # System managed field - too complex for manual editing
    display_snippet: null  # Raw JSON error data not suitable for display

```
